### PR TITLE
Fix PowerShell command when PS print some lines each startup

### PR DESCRIPTION
**Pull request by KindDragon**

### CODE REVIEW

**Review by yuslepukhin — COMMENTED** [review]
I have two concerns here unless I am reading this wrong. The updated PS command writes output in the same file as it reads. This has two consequences: 1) We loose output control in the execute_process statement which may be more maintainable 2) the subsequent configure_file command expects the input from ${file_path}.cmake which we are no longer writing to.

**Comment by KindDragon** [comment]
No, it write to `${ntv_file_path}.cmake` (`Set-Content \"${ntv_file_path}.cmake\"`)

**Comment by KindDragon** [comment]
BTW Do you plan to merge this fork to `jemalloc` repository?

**Comment by yuslepukhin** [comment]
@KindDragon I have no authority over the jemalloc repo. Jason kindly forked for experimental purposes. I hear he is working on CMake build and hopefully this is useful for his reference. But no ETA.

**Comment by yuslepukhin** [comment]
@KindDragon Thank you for your contribution

**Pull request merged**
